%YAML 1.2
---

n_runs: 1

# Runs Graphical Interface

graphical: True

log_level: info

# Agents Properties

agent_type: Roles #Random #PathPlanner #IDsSocialConventions #QuadrantsSocialConventions #Roles #Debug

Random: 
  nr_passengers: 4
  nr_agents: 4

PathPlanner:
  nr_passengers: 4
  nr_agents: 4

QuadrantsSocialConventions:
    nr_passengers: 10
    nr_agents: 5

IDsSocialConventions:
    nr_passengers: 10
    nr_agents: 5

Roles:
  nr_passengers: 10
  nr_agents: 4

Debug:
    nr_passengers: 4
    nr_agents: 1

