%YAML 1.2
---

# Runs Graphical Interface

graphical: True

# Agents Properties

agent_type: PathPlanner #Random #PathPlanner #Deliberative #Debug

Random: 
  nr_passengers: 4
  nr_agents: 4

Deliberative:
    nr_passengers: 4
    nr_agents: 4

PathPlanner:
  nr_passengers: 4
  nr_agents: 4

Debug:
    nr_passengers: 4
    nr_agents: 1

